name: Import release

on:
  repository_dispatch:
    inputs:
      tag:
        required: true
        description: A release tag from the iOS repo to import

jobs:
  import:
    runs-on: macos-latest
    env:
      MAIN_REPO_OWNER: BranchMetrics
      MAIN_REPO_REPO: ios-branch-deep-linking-attribution
    steps:
      - name: Check out SPM repo
        uses: actions/checkout@v3
      - name: Check out main iOS repo
        uses: actions/checkout@v3
        with:
          repository: ${{ env.MAIN_REPO_OWNER }}/${{ env.MAIN_REPO_REPO }}
          ref: ${{ github.event.client_payload.tag }}
          path: .ios-repo
      - name: Import release ${{ github.event.client_payload.tag }}
        id: import-release
        uses: ./.github/actions/import-release
        with:
          tag: ${{ github.event.client_payload.tag }}
      - name: Create release
        uses: actions/github-script@v4
        with:
          result-encoding: string
          script: |
            const tag = '${{ github.event.client_payload.tag }}';
            const sha = '${{ steps.import-release.outputs.sha }}';
            const mainRepoOwner = '${{ env.MAIN_REPO_OWNER }}';
            const mainRepoRepo = '${{ env.MAIN_REPO_REPO }}';

            const { data } = await github.repos.getReleaseByTag({
              owner: mainRepoOwner,
              repo: mainRepoRepo,
              tag,
            });

            await github.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              target_commitish: sha,
              tag_name: tag,
              name: tag,
              body: `Mirror of https://github.com/${mainRepoOwner}/${mainRepoRepo}/releases/${tag}`,
              prerelease: data.prerelease,
            });
